# Generated by Django 2.1.5 on 2019-04-20 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ville', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('quartier', models.CharField(max_length=20)),
                ('codePostal', models.IntegerField()),
                ('rue', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=10, unique=True)),
                ('nbrePlaces', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=10)),
                ('adresse', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Management.Adresse')),
                ('bus', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Management.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('niveau', models.CharField(choices=[('Maternelle', 'Maternelle'), ('Primaire', 'Primaire'), ('College', 'Collège'), ('Lycee', 'Lycée')], default='', max_length=10)),
                ('nom', models.CharField(max_length=30, unique=True)),
                ('adresse', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Management.Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('cne', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=10)),
                ('adresse', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Management.Adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=10)),
                ('adresse', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Management.Adresse')),
                ('enfant', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Management.Etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='ecole',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Management.Ecole'),
        ),
    ]
