# Generated by Django 2.1.5 on 2019-04-20 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chauffeur',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='adresse',
        ),
        migrations.AddField(
            model_name='bus',
            name='ecole',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Management.Ecole'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='cne',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
