# Generated by Django 2.1.5 on 2019-04-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_remove_etudiant_cne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='enfant',
            new_name='etudiant',
        ),
    ]
